[boris]
  version = 1

[build.dist-7-10-core]
  command = [["master", "build", "dist-7-10", "-C", "projector-core"]]

[build.branches-7-10-core]
  command = [["master", "build", "branches-7-10", "-C", "projector-core"]]

[build.dist-7-10-cli]
  command = [["master", "build", "dist-7-10", "-C", "projector-cli"]]

[build.branches-7-10-cli]
  command = [["master", "build", "branches-7-10", "-C", "projector-cli"]]

[build.dist-7-10-html-haskell]
  command = [["master", "build", "dist-7-10", "-C", "projector-html-haskell"]]

[build.branches-7-10-html-haskell]
  command = [["master", "build", "branches-7-10", "-C", "projector-html-haskell"]]

[build.dist-7-10-html]
  command = [
      ["master", "build", "dist-7-10", "-C", "projector-html"]
    , ["master", "build", "dist-doc", "-C", "projector-html"]
    ]

[build.branches-7-10-html]
  command = [
      ["master", "build", "branches-7-10", "-C", "projector-html"]
    , ["master", "build", "branches-doc", "-C", "projector-html"]
    ]

[build.dist-7-10-html-runtime-hs]
  command = [["master", "build", "dist-7-10", "-C", "projector-html-runtime-hs"]]

[build.branches-7-10-html-runtime-hs]
  command = [["master", "build", "branches-7-10", "-C", "projector-html-runtime-hs"]]

[build.dist-0-9-3-html-runtime-purs]
  command = [["master", "build", "dist-0-9-3", "-C", "projector-html-runtime-purs"]]

[build.branches-0-9-3-html-runtime-purs]
  command = [["master", "build", "branches-0-9-3", "-C", "projector-html-runtime-purs"]]


[build.dist-0-9-3-html-runtime-purs-pux]
  command = [["master", "build", "dist-0-9-3", "-C", "projector-html-runtime-purs-pux"]]

[build.branches-0-9-3-html-runtime-purs-pux]
  command = [["master", "build", "branches-0-9-3", "-C", "projector-html-runtime-purs-pux"]]


[build.dist-7-10-html-purs]
  command = [["master", "build", "dist-7-10", "-C", "projector-html-purs"]]

[build.branches-7-10-html-purs]
  command = [["master", "build", "branches-7-10", "-C", "projector-html-purs"]]

[build.dist-validate]
  command = [["validate-respect"]]

[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]

