[boris]
  version = 1
[build.dist]
  git = "refs/heads/master"
[build.branches]
  git = "refs/heads/topic/*"
[build.dist-7-8]
  git = "refs/heads/master"
[build.dist-7-10]
  git = "refs/heads/master"
[build.branches-7-8]
  git = "refs/heads/topic/*"
[build.branches-7-10]
  git = "refs/heads/topic/*"
[build.validate]
  git = "refs/heads/master"
